/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Contacts = {
  _id: string;
  _type: "contacts";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contacts?: Array<{
    contactType?: string;
    contactUrl?: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProjectDetails = {
  _id: string;
  _type: "projectDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName?: string;
  projectDate?: string;
  techStack?: Array<string>;
  projectRole?: string;
  projectOverview?: string;
  projectImage?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  projectFeatures?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Technologies = {
  _id: string;
  _type: "technologies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  technologyCategory?: Array<{
    technologyCategory?: string;
    technologyList?: Array<string>;
    _key: string;
  }>;
};

export type Techstack = {
  _id: string;
  _type: "techstack";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  techstack?: Array<string>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projects?: Array<{
    name?: string;
    slug?: Slug;
    projectDescription?: string;
    projectURL?: string;
    urlDisplay?: string;
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  about?: string;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  avatarImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  subtitle?: string;
  welcomeMessage?: string;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  experienceName?: Array<{
    companyName?: string;
    jobTitle?: string;
    startDate?: string;
    endDate?: string;
    companyLocation?: string;
    jobDescription?: string;
    _key: string;
  }>;
};

export type CurrentBuilding = {
  _id: string;
  _type: "currentBuilding";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  taskName?: Array<{
    taskName?: string;
    techstackUsed?: Array<string>;
    status?: string;
    _key: string;
  }>;
};

export type Certifications = {
  _id: string;
  _type: "certifications";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  certificationName?: Array<{
    certificationName?: string;
    certificationIssuer?: string;
    certificationDate?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Contacts
  | SanityImageAssetReference
  | ProjectDetails
  | SanityImageCrop
  | SanityImageHotspot
  | Technologies
  | Techstack
  | Project
  | Slug
  | Profile
  | Hero
  | Experience
  | CurrentBuilding
  | Certifications
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: components/sections/about-me.tsx
// Variable: PROFILE_QUERY
// Query: *[_id == "profile"][0]{  profileImage,  about}
export type PROFILE_QUERY_RESULT =
  | {
      profileImage: null;
      about: null;
    }
  | {
      profileImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      about: string | null;
    }
  | null;

// Source: components/sections/tech-stack.tsx
// Variable: TECHSTACK_QUERY
// Query: *[_id == "techstack"][0]{  techstack}
export type TECHSTACK_QUERY_RESULT =
  | {
      techstack: null;
    }
  | {
      techstack: Array<string> | null;
    }
  | null;

// Source: components/sections/tools.tsx
// Variable: TOOLS_QUERY
// Query: *[_id == "technologies"][0]{  technologyCategory[]{    _key,    technologyCategory,    technologyList  }}
export type TOOLS_QUERY_RESULT =
  | {
      technologyCategory: null;
    }
  | {
      technologyCategory: Array<{
        _key: string;
        technologyCategory: string | null;
        technologyList: Array<string> | null;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "profile"][0]{\n  profileImage,\n  about\n}': PROFILE_QUERY_RESULT;
    '*[_id == "techstack"][0]{\n  techstack\n}': TECHSTACK_QUERY_RESULT;
    '*[_id == "technologies"][0]{\n  technologyCategory[]{\n    _key,\n    technologyCategory,\n    technologyList\n  }\n}': TOOLS_QUERY_RESULT;
  }
}
